version: '2'
services:
  trivy:
    image: aquasec/trivy:latest
    entrypoint: ""
    working_dir: /src
    environment:
      TRIVY_TIMEOUT: '30m'
    volumes:
      - cache:/root/.cache/
      - .:/src
  anybadge:
    image: registry.gitlab.com/fixl/docker-anybadge:latest
    entrypoint: ""
    working_dir: /src
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src

  firebase:
    image: firebase-emulator-suite:latest
    working_dir: /src
    environment:
      FIREBASE_PROJECT_ID: foo
#      HOSTING: 'true'
#      FUNCTIONS: 'true'
#      FIRESTORE: 'true'
#      PUBSUB: 'true'
#      DATABASE: 'true'
#      AUTH: 'true'
      STORAGE: 'true'

volumes:
  cache:
